development:
  adapter: mysql2
  encoding: utf8
  database: drf
  username: root
  password: 
  host: localhost
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: drafter
  username: drafter
  password: drafter
  host: localhost
  timeout: 5000
